 CREATE TABLE TB_CLIENT (
 	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
 	NOME VARCHAR(100)
 );
 
 CREATE TABLE TB_PRODUCT(
 	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
 	DESCRIPTION VARCHAR(100),
 	UNIT_PRICE NUMERIC(20,2)
 );
 
 
 CREATE TABLE TB_ORDER (
 	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
 	CLIENT_ID INTEGER REFERENCES TB_CLIENT(ID),
 	DATE_ORDER TIMESTAMP,
 	STATUS VARCHAR(20),
 	TOTAL NUMERIC(20,2)
 );
 
  CREATE TABLE TB_ITEM_ORDER(
 	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
 	ORDER_ID INTEGER REFERENCES TB_ORDER(ID),
 	PRODUCT_ID INTEGER REFERENCES TB_PRODUCT(ID),
 	AMOUNT INTEGER
 );